name: Отчет об ошибке
description: Сообщите об ошибке.
title: "[Название ошибки]: "
labels: ["Номер"]
body:
  - type: textarea
    id: description-3-1-2
    attributes:
      label: Описание деффекта
      description: Подробное описание деффекта
      placeholder: подсказка
    validations:
      required: true #поле обязательно для заполнения
  - type: dropdown
    id: description-1-2-2
    attributes:
      label: В какой игре вышла ошибка
      description: Выберете название игры
      options:
       - Cyberpunk 2077
       - The Witcher 3
       - Dark Souls III
       - Red Dead Redemption 2
       - Doom Eternal
       - Control
       - Elden Ring
       - другое...
    validations:
      required: true
  - type: checkboxes
    id:  description-1-1-3
    attributes:
      label: Выберете какие виды ошибок были
      description: Выберете 1 или несколько флажков
      options:
      - label: флажок 1
        required: true #флажок обязателен или нет
      - label: флажок 2
      - label: флажок 3
      - label: флажок 4
      - label: флажок 5
       
