name: Отчет об ошибке
description: Сообщите об ошибке.
title: "[Название ошибки]: "
labels: ["Номер"]
body:
  - type: textarea
    id: description-3-1-1
    attributes:
      label: Описание деффекта
      description: Подробное описание деффекта
      placeholder: подсказка
    validations:
      required: true #поле обязательно для заполнения
  - type: textarea
    id: description-3-1-2
    attributes:
      label: Ожиадемый результат
      description: Описание ожидаемого результата
      placeholder: текст
    validations:
      required: true #поле обязательно для заполнения
  - type: textarea
    id: description-3-1-3
    attributes:
      label: Фактический результат
      description: Описание фактического результата
      placeholder: текст
    validations:
      required: true #поле обязательно для заполнения
  - type: textarea
    id: description-3-1-4
    attributes:
      label: Скрин/Доп материалы
      description: Доп материалы
      placeholder: скрин
    validations:
      required: false #поле обязательно для заполнения    
  - type: dropdown
    id: description-1-1-1
    attributes:
      label: Среда выполнения
      description: Выберете среду
      options:
       - Uniti
       - PyCharm
       - Android Studio
    validations:
      required: true
  - type: checkboxes
    id:  description-2-1-1
    attributes:
      label: Приоритет
      description: Выберете приоритет проблемы
      options:
      - label: Немедленная
      - label: Высокий
      - label: Средний
      - label: Низкий
    validations:
      required: true
  - type: checkboxes
    id:  description-2-1-2
    attributes:
      label: Серьезность
      description: Выберете серьезность проблемы
      options:
      - label: Критическая
      - label: Высокий
      - label: Средний
      - label: Низкий
    validations:
      required: true
